spring.application.name=taskmanager

spring.datasource.username=postgres
spring.datasource.password=2002
spring.datasource.url=jdbc:postgresql://localhost:5432/slms2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update